# Generated by Django 3.0.7 on 2022-01-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('total_repayment', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('crm_loan_id', models.IntegerField(blank=True, null=True)),
                ('repayment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('purpose', models.TextField()),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50)),
                ('payment_duration', models.IntegerField(null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('admin_fee', models.DecimalField(blank=True, decimal_places=2, default=2500.0, max_digits=50)),
                ('penalties', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Completed', 'Completed')], max_length=90, null=True)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'NGN')], default='NGN', max_length=90, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('contract_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Completed', 'Completed')], max_length=90, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('paid', models.BooleanField(default=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=50)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='CRMLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('clientId', models.CharField(blank=True, max_length=12)),
                ('loanId', models.CharField(blank=True, max_length=12)),
                ('payment_duration', models.IntegerField(null=True)),
                ('contract_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Completed', 'Completed')], max_length=90, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Withdrawn', 'Withdrawn'), ('Denied', 'Denied'), ('Approved', 'Approved')], max_length=10, null=True)),
                ('contract_id', models.CharField(blank=True, max_length=100, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('signers_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_pdf_url', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('investment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Investment')),
                ('loan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.Loan')),
            ],
        ),
    ]
