# Generated by Django 3.0.7 on 2022-01-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Bank-Transfer', 'Bank-Transfer'), ('Top-Up', 'Top-Up'), ('Airtime', 'Airtime'), ('Data', 'Data'), ('Bill', 'Bill'), ('Tuition', 'Tuition'), ('loan', 'loan'), ('loan-repayment', 'Loan Repayment')], max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'Initiated Trasaction'), ('SPV', 'PENDING VALIDATION'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], default=[('NEW', 'Initiated Trasaction'), ('SPV', 'PENDING VALIDATION'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], max_length=200)),
                ('type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('narration', models.TextField(blank=True, max_length=200, null=True)),
                ('payment_reference', models.CharField(max_length=200)),
                ('payment_response', models.CharField(max_length=200)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=11)),
                ('comment', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('credit_date', models.DateTimeField(auto_now_add=True)),
                ('is_test', models.BooleanField(default=1, editable=False)),
                ('transaction_type', models.CharField(blank=True, editable=False, max_length=250)),
                ('ledger_entity', models.CharField(editable=False, max_length=20)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
    ]
