# Generated by Django 3.0.7 on 2022-01-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.TextField()),
                ('validated', models.BooleanField(default=True)),
                ('bank_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_date', models.DateTimeField(null=True)),
                ('cleared_date', models.DateTimeField(null=True)),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('ref', models.CharField(max_length=50, null=True)),
                ('bank', models.CharField(max_length=50, null=True)),
                ('customer', models.CharField(max_length=50, null=True)),
                ('account', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Register_Client')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_year_income', models.IntegerField(null=True)),
                ('projected_yearly_income', models.IntegerField(null=True)),
                ('transactions', models.IntegerField(null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Register_Client')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('bvn', models.CharField(max_length=50, null=True)),
                ('score', models.CharField(max_length=50, null=True)),
                ('env', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('dob', models.DateField(null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Register_Client')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('available_balance', models.IntegerField(null=True)),
                ('ledger_balance', models.IntegerField(null=True)),
                ('currency', models.CharField(max_length=255, null=True)),
                ('connected', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('env', models.CharField(max_length=50, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Register_Client')),
            ],
        ),
    ]
