# Generated by Django 3.0.7 on 2022-01-24 14:54

from django.db import migrations, models
import django.db.models.deletion
import settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='users.Business')),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, default=50000.0, max_digits=11, validators=[settings.models.validate_daily])),
                ('daily_withdraw_limit', models.DecimalField(decimal_places=2, default=50000.0, max_digits=11, validators=[settings.models.validate_daily])),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=11, validators=[settings.models.validate_per_transaction])),
            ],
        ),
        migrations.CreateModel(
            name='IndividualSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='users.Individual')),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, default=50000.0, max_digits=11, validators=[settings.models.validate_daily])),
                ('daily_withdraw_limit', models.DecimalField(decimal_places=2, default=50000.0, max_digits=11, validators=[settings.models.validate_daily])),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=11, validators=[settings.models.validate_per_transaction])),
            ],
        ),
    ]
