# Generated by Django 3.0.7 on 2022-01-24 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WitMono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=None, max_length=90)),
                ('name', models.CharField(max_length=150, null=True)),
                ('bvn', models.CharField(max_length=90, null=True)),
                ('acct_number', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('income', models.FloatField(null=True)),
                ('credit_score', models.FloatField(null=True)),
                ('uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('wallet_id', models.UUIDField(default=uuid.uuid4)),
                ('pocketReferenceId', models.CharField(default=None, max_length=200, null=True)),
                ('pocketAccountNumber', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('customerExternalRef', models.CharField(default=None, max_length=200, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('lastBalance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=90, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accountName', models.CharField(default=None, max_length=90)),
                ('accountNumber', models.CharField(default=None, max_length=90)),
                ('bankCode', models.CharField(default=None, max_length=40)),
                ('bankName', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Remita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('createdOn', models.CharField(max_length=200)),
                ('completedOn', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('completed', models.BooleanField(default=True)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('providerCode', models.CharField(max_length=50, null=True)),
                ('transactionReference', models.CharField(max_length=50)),
                ('paymentReference', models.CharField(max_length=50)),
                ('merchantCode', models.CharField(max_length=50)),
                ('merchantName', models.CharField(max_length=100)),
                ('settleInstantly', models.BooleanField(null=True)),
                ('payableAmount', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.ReservedAccounts')),
            ],
        ),
    ]
