# Generated by Django 3.0.7 on 2022-02-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='lastBalance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
